186730392 animate arrows
concord-consortium/sampler pull request #20
Opened 2024-02-21 21:25 UTC by eireland

Animates the arrow when Start button is clicked. Animation runs for the number of samples set.
The trigger to animate the arrow should be adjusted later when the devices are animated.

2024-02-22 18:03 UTC, lublagg requested changes
Looks good, just a console.log to remove.
Right now all the arrows animate at the same time, but they'll need to animate in sequence when we get there, or also not animate at all if the speed is set to "fastest". Is that what you were referring to when you wrote, "The trigger to animate the arrow should be adjusted later when the devices are animated"?

2024-02-24 11:38 UTC, eireland commented on src/components/model/arrow.tsx
> +console.log("modelisrunning", modelIsRunning);
Yes, the trigger comment was to remind us that the trigger to animate needs to be implemented because they depend on the device animation to finish, and the timing for the arrow animation to finish and the next device animation start needs to be coordinated.

2024-02-26 14:27 UTC, dougmartin commented
Skipping this review since @lublagg already reviewed it.

2024-02-26 15:51 UTC, lublagg approved these changes

2024-02-28 17:04 UTC, merged