Use global state context instead of drilling down props.
concord-consortium/sampler pull request #24
Opened 2024-02-23 18:46 UTC by lublagg

2024-02-24 21:10 UTC, eireland requested changes
Nice job on the refactoring! Found a few more places that may be could be refactored. I was going back and forth on whether to move the spinner specific handlers into the spinner view (`handleStartDrag`, and `handleDeleteWege`), but I'll leave it up to you.

2024-02-24 21:13 UTC, eireland commented
Yes! Thank you for doing this. I was thinking the same thing when we started work on it.

2024-02-26 14:22 UTC, dougmartin commented
Skipping this review since @eireland already reviewed it.

2024-02-28 02:42 UTC, eireland approved these changes
Looks good. I did leave a comment re trimming column names so that checking for uniqueness is easier.

2024-02-28 02:42 UTC, eireland commented on src/components/model/column.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Remove unused var disable since it is no longer used.

2024-02-28 20:40 UTC, lublagg commented on src/components/model/column-header.tsx
> +    const newName = getNewColumnName(columnName, model.columns, column.id);
Done, good catch :)

2024-02-28 21:03 UTC, merged